-- Create strategy_reports table for Recommendations module
CREATE TABLE IF NOT EXISTS strategy_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    html_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_strategy_reports_project ON strategy_reports(project_id);
CREATE INDEX IF NOT EXISTS idx_strategy_reports_created ON strategy_reports(created_at DESC);

-- Add comment
COMMENT ON TABLE strategy_reports IS 'Stores HTML optimization strategy reports generated by AI';

-- Enable Row Level Security (RLS)
ALTER TABLE strategy_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view reports for projects they own
CREATE POLICY "Users can view reports for their projects" ON strategy_reports
    FOR SELECT
    USING (
        project_id IN (
            SELECT id FROM projects WHERE user_id = auth.uid()
        )
    );

-- Policy: Users can create reports for projects they own
CREATE POLICY "Users can create reports for their projects" ON strategy_reports
    FOR INSERT
    WITH CHECK (
        project_id IN (
            SELECT id FROM projects WHERE user_id = auth.uid()
        )
    );

-- Policy: Users can delete reports for projects they own
CREATE POLICY "Users can delete reports for their projects" ON strategy_reports
    FOR DELETE
    USING (
        project_id IN (
            SELECT id FROM projects WHERE user_id = auth.uid()
        )
    );
